# Generated by Django 4.2.4 on 2023-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('nascimento', models.DateField()),
                ('cpf', models.TextField(max_length=11)),
                ('email', models.EmailField(max_length=255)),
                ('numero', models.TextField(max_length=11)),
                ('unidade', models.TextField(max_length=100)),
            ],
        ),
    ]
